In [7]:
import torch 

In [29]:
review = "I love this product, but the price is a bit expensive."
# Tokenized review
tokens = review.lower().split()
# Word embeddings (simplified for illustration)
word_embeddings = {
    "i": [0.1, 0.2, 0.3],
    "love": [0.4, 0.5, 0.6],
    "this": [0.7, 0.8, 0.9],
    "product": [0.2, 0.3, 0.4],
    "but": [0.3, 0.4, 0.5],
    "the": [0.6, 0.7, 0.8],
    "price": [0.8, 0.9, 1.0],
    "is": [0.2, 0.3, 0.4],
    "a": [0.1, 0.1, 0.1],
    "bit": [0.2, 0.2, 0.2],
    "expensive": [0.9, 1.0, 1.1]
}

# aspect 
aspect_embedding = [0.8, 0.9, 1.0]  # Example aspect embedding for "price"

In [33]:
review_embeddings = [
    [0.1, 0.2, 0.3],  # "i"
    [0.4, 0.5, 0.6],  # "love"
    [0.7, 0.8, 0.9],  # "this"
    [0.2, 0.3, 0.4],  # "product"
    [0.3, 0.4, 0.5],  # "but"
    [0.6, 0.7, 0.8],  # "the"
    [0.8, 0.9, 1.0],  # "price"
    [0.2, 0.3, 0.4],  # "is"
    [0.1, 0.1, 0.1],  # "a"
    [0.2, 0.2, 0.2],  # "bit"
    [0.9, 1.0, 1.1]   # "expensive"
]


aspect_transformations = []

for word_embedding in review_embeddings:
    # Calculate the transformation for the current word and aspect
    word_aspect_transformation = [a * w for a, w in zip(aspect_embedding, word_embedding)]
    print(word_aspect_transformation)
    aspect_transformations.append(word_aspect_transformation)

# Aspect transformations for each word in the review
aspect_transformations

[0.08000000000000002, 0.18000000000000002, 0.3]
[0.32000000000000006, 0.45, 0.6]
[0.5599999999999999, 0.7200000000000001, 0.9]
[0.16000000000000003, 0.27, 0.4]
[0.24, 0.36000000000000004, 0.5]
[0.48, 0.63, 0.8]
[0.6400000000000001, 0.81, 1.0]
[0.16000000000000003, 0.27, 0.4]
[0.08000000000000002, 0.09000000000000001, 0.1]
[0.16000000000000003, 0.18000000000000002, 0.2]
[0.7200000000000001, 0.9, 1.1]


[[0.08000000000000002, 0.18000000000000002, 0.3],
 [0.32000000000000006, 0.45, 0.6],
 [0.5599999999999999, 0.7200000000000001, 0.9],
 [0.16000000000000003, 0.27, 0.4],
 [0.24, 0.36000000000000004, 0.5],
 [0.48, 0.63, 0.8],
 [0.6400000000000001, 0.81, 1.0],
 [0.16000000000000003, 0.27, 0.4],
 [0.08000000000000002, 0.09000000000000001, 0.1],
 [0.16000000000000003, 0.18000000000000002, 0.2],
 [0.7200000000000001, 0.9, 1.1]]

In [41]:
import torch

# Define the aspects
aspects = ["price", "product", "quality"]

# Reviews
reviews = [
    "The price is a bit high, but the product is great.",
    "I love the quality of this product.",
    "The price is reasonable, and the product is average in quality."
]

# Tokenized reviews
tokenized_reviews = [review.lower().split() for review in reviews]

# Word embeddings (simplified for illustration)
word_embeddings = {
    "the": torch.randn(3),
    "price": torch.randn(3),
    "is": torch.randn(3),
    "a": torch.randn(3),
    "bit": torch.randn(3),
    "high,": torch.randn(3),
    "but": torch.randn(3),
    "product": torch.randn(3),
    "great.": torch.randn(3),
    "i": torch.randn(3),
    "love": torch.randn(3),
    "quality": torch.randn(3),
    "of": torch.randn(3),
    "this": torch.randn(3),
    "reasonable,": torch.randn(3),
    "and": torch.randn(3),
    "average": torch.randn(3),
    "in": torch.randn(3),
}

# Aspect embeddings (simplified for illustration)
aspect_embeddings = {
    "price": torch.randn(3),
    "product": torch.randn(3),
    "quality": torch.randn(3)
}

aspect_transformations = []

for review_tokens in tokenized_reviews:
    review_aspect_transformations = []
    
    for word in review_tokens:
        word_embedding = word_embeddings.get(word, torch.zeros(3))
        word_aspect_transformation = torch.stack([torch.matmul(word_embedding, aspect_embeddings[aspect]) for aspect in aspects])
        review_aspect_transformations.append(word_aspect_transformation)
    
    aspect_transformations.append(review_aspect_transformations)

# Aspect transformations for each word in each review, resulting in a 3D tensor


In [43]:
aspect_transformations

[[tensor([-0.5735, -2.4747, -1.1778]),
  tensor([-0.0869, -0.2441, -0.1231]),
  tensor([-0.3181, -0.9847, -0.3224]),
  tensor([ 2.7821, -3.2970, -1.7040]),
  tensor([ 0.1232, -0.4707, -0.3938]),
  tensor([-2.1362,  2.3681,  0.8428]),
  tensor([ 0.6788, -1.7023, -0.6206]),
  tensor([-0.5735, -2.4747, -1.1778]),
  tensor([-0.9695,  1.4394,  1.3292]),
  tensor([-0.3181, -0.9847, -0.3224]),
  tensor([ 0.0577, -1.4307, -0.4303])],
 [tensor([ 1.4453, -2.1314, -0.4212]),
  tensor([ 0.0274, -0.1113, -0.6192]),
  tensor([-0.5735, -2.4747, -1.1778]),
  tensor([-1.0788,  1.0021, -0.0461]),
  tensor([ 0.3283, -0.7831, -0.0120]),
  tensor([-1.4593,  4.3738,  1.4325]),
  tensor([0., 0., 0.])],
 [tensor([-0.5735, -2.4747, -1.1778]),
  tensor([-0.0869, -0.2441, -0.1231]),
  tensor([-0.3181, -0.9847, -0.3224]),
  tensor([ 0.2203,  0.9050, -0.1024]),
  tensor([ 2.1184, -3.5363, -1.5841]),
  tensor([-0.5735, -2.4747, -1.1778]),
  tensor([-0.9695,  1.4394,  1.3292]),
  tensor([-0.3181, -0.9847, -0.3224]),